# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 7506be424438b2b3833d97fa242939fee0c9f49fb41e50309795336cbae39dcfcced3269d098ed055f383112fc3765beab0d2e8a79f519c526a9b5d69b4f7cca

test:
  secret_key_base: e1261df4d59719c04760055b28c79daa3956434397a3e6cec5377c0504b3e0d540b8cff962cb6b9333e2606fcff2aff2e91feabf69b2b771098bbae88133ac7a

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
